### ISSUE TITLE
Issue with global stats?

### ISSUE THREAD

**Issue by volumen1** [graywolf336/CasinoSlots#49]
I have three different slot machines and it loks like the stats.yml tracking for each of them is fine, but I'm not sure how the global: is calculating won/lost.  It seems a little goofy.  Here is my example.  

```yml
global:
  spins: 112
  wins: 21
  losts: 91
  won: 35251.0
  lost: 63745.0
types:
  default:
    spins: 72
    wins: 12
    losts: 60
    won: 629.0
    lost: 1170.0
  highstakes:
    spins: 10
    wins: 0
    losts: 10
    won: 0.0
    lost: 1000.0
  penny:
    spins: 30
    wins: 9
    losts: 21
    won: 24.0
    lost: 30.0
```
Thanks
